title: "CloudSim Plus" 
description: "State-of-the-art Framework 🏗 for Cloud Computing ⛅️ Simulation: a modern, full-featured, easier-to-use, highly extensible 🧩, faster 🚀 and more accurate ☕️ Java 17+ tool for cloud computing research 🎓" 
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect
encoding: utf-8
  
exclude:
  - CONTRIBUTING.md
  - .github
  - .gitignore

plugins:
  - jekyll-mentions
  - jemoji

webrick:
  headers:
    keywords: "CloudSim Plus,CloudSim,Cloud Computing,Simulation,Framework,IaaS,PaaS,SaaS,Java 8,Maven,Maven Central"
